[package]
name = "note"
version = "0.1.0"
edition = "2021"
description = "Command line note taker"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
xdg = "2.4.1"
chrono = "0.4.23"
